### ISSUE TITLE
[Bug] Keeps forgetting XMPP account.

### ISSUE THREAD

**Issue by polemion** [isotoxin/isotoxin#12]
Since last version it keeps forgetting the XMPP (jabber) account.

**Comment by vatterspun** [comment]
What version are you using?

**Comment by polemion** [comment]
0.4.514 not the portable.

After PC sleep.

**Comment by polemion** [comment]
I tried the PortableApps version, same problem.

It also happens when the program starts.

**Comment by vatterspun** [comment]
> It also happens to the PortableApps version.

Thanks for checking.  I ask because a number of programs from that admittedly great platform will intermittently just forget about your settings.  I've been frustrated for a long time with Notepad++ dumping it's settings.

**Comment by polemion** [comment]
> Thanks for checking.

No problem. I have also tried a new install in a different computer and I still have the same problem.

Any ideas why?

**Comment by polemion** [comment]
Any ideas on why this is happening?

I mean besides [vatterspun](https://github.com/vatterspun) nobody seems to care.

Is there any temporal solution at least? Can I edit something here or there?

**Comment by vatterspun** [comment]
> I mean besides vatterspun nobody seems to care.

The developer has been remarkably responsive and cool, which is part of why I try to help out on his Github page.  It's easily possible he's just got a very busy last few weeks.  Unless he's received some crazy donations I don't know about (which is super rare in projects like this one) he's not getting paid to work on this.

**Comment by polemion** [comment]
> he's not getting paid to work on this

I have never asked from anyone, especially from developers, for favors, neither have I pointed at the developer himself.

I believe there is a difference between working to something and answering to something. Especially in a quiet git like this.

I am sure he is responsible and cool, even though he never answered in 2 different bug reports of the 2 previous version in his forum after 2 months. It is my luck I guess.

I will not bother him again. Thank you for your time.

**Comment by vatterspun** [comment]
I wish you hadn't closed it.  Certainly your time is valuable too and I have no doubt that the author appreciates you submitting the bug.  I'm just trying to make sure the dev knows we appreciate his work and if he's gone for some period due to (for example) personal issues that it doesn't mean his users stopped appreciating the effort.
