### ISSUE TITLE
[Feature request] Folder share capability

### ISSUE THREAD

**Issue by vatterspun** [isotoxin/isotoxin#6]
I'm a big fan of the program and this is very firmly in the "nice to have" category.  Feel free to ignore and close in favor of just making this simple and easy to use.  Arguably, Isotoxin is an alternative to other programs with poor privacy / security, not a file sharing program.

**Current behavior:**

Want to make my files available to recipient.  Inform what files are available or send a list.  Then manually send requested files.

**Requested behavior:**

Make a folder available so the user can download files as needed.

**Possible issues:**

* Uploads may interfere with other Isotoxin operations like VoIP or other programs
* This may result in additional requests such as having downloads resume (especially for larger files)

**Comment by isotoxin** [comment]
Good feature, but it can be implemented only for Isotoxin-Isotoxin connections.
I will implement it as soon as possible.

**Comment by smaragdus** [comment]
@**vatterspun** & @**isotoxin**
This will be a useful feature but I suppose it won't be very easy to be implemented.
There is such a feature in an ancient but still working messenger- **BitWise** (http://www.bitwiseim.com/), screen-shot- https://s20.postimg.org/8jqyu2nbh/Bit_Wise_1.png

**Comment by vatterspun** [comment]
> I will implement it as soon as possible.

Very cool, thank you.

> BitWise

Oh - I had no idea.  Sweet.

**Comment by isotoxin** [comment]
Folder share feature has been implemented in 0.4.511

**Comment by smaragdus** [comment]
Thank you very much for implementing this useful feature. I notified The Portable Freeware community:
https://www.portablefreeware.com/forums/viewtopic.php?p=85990#p85990
