### ISSUE TITLE
When Using 32-bit Isotoxin 0.4.503, There is a Prompt to upgrade to  the 0.4.503 x64 Version On Windows 10 Anniversary Edition x64

### ISSUE THREAD

**Issue by rocksinboxes** [isotoxin/isotoxin#8]
When I use Isotoxin 0.4.503 32-bit or the 32-bit portableapps edition,  I am prompted to upgrade  to the the latest version which says is Isotoxin 0.4.503 x64. I am running Windows 10 x64 Anniversary Edition on a Surface Pro 3. Is this by design or a bug? I hope this helps. Thanks. 

<img width="599" alt="isotoxin_screenshot" src="https://cloud.githubusercontent.com/assets/1304386/22314131/e7dc8de6-e314-11e6-93b1-73e5874c9998.png">

**Comment by isotoxin** [comment]
No. This is not bug.
Isotoxin detects that it run on 64 bit windows and tries to upgrade self to 64 bit version.
It is possible to disable such behavior:
- Open settings
- Enable advance settings (check `"I'm power user. Please, show me advanced settings"` in Profile:General)
- Press `"Save"` and then open settings again. Now you see advanced settings
- Check `"Disable autoupdate to 64 bit version"` in Advanced:Misc
- Press `"Save"`
