### ISSUE TITLE
[Crash] When loading LAN network, both the plugin manager and the plugin crash

### ISSUE THREAD

**Issue by Sidefix** [isotoxin/isotoxin#9]
When launching 0.4.503 with a LAN network already saved from a previous session, the LAN network will not be loaded, and the plugin manager and the lan plugin will crash. This didn't occur with the previous isotoxin build.

Checking the Settings menu after the crash occurs displays the LAN network as 'not yet created or loaded'

Both crash logs (which are too big to attach here) you can find here:
https://1drv.ms/f/s!AjXIJDi52MKGlpIC9Io59jWD_WX6AA

**Comment by isotoxin** [comment]
LAN crash was fixed. Please upgrade to 0.4.511
